### ISSUE TITLE
transcribed text doesn't go to clipboard

### ISSUE THREAD

**Issue by tonylampada** [martin-opensky/whisper-assistant-vscode#3]
Recorded a video. 
https://www.loom.com/share/4e6bb1a7ff7542ca9bbb21b08767758e

Happy to help if you need more info

**Comment by martin-opensky** [comment]
Hey @tonylampada,

The error appears to be permissions related, when trying to save the audio recording to a .wav file.

The way the process works is:
- SoX records your mic (which appears to be working)
- This audio is saved to a temp .wav recording
- Whisper processes the temp .wav recording to transcribe the audio
- The recording is deleted and the transcription saved to clipboard.

My gut is that the issue is related to the Roboflow dev container, which is causing some issues.
Please test by opening a directory on your file system i.e. File -> Open Folder and then give it a try.  A .whisper directory should be created and you should see the .wav file being created and then deleted once the process is completed.

**Comment by tonylampada** [comment]
Indeed I see it created /roboflow/.whisper in the devcontainer:
Even after chmod 777 on .whisper nothing gets written into that folder (not even for a short time)

Maybe it's confusing the devcontainer filesystem paths with the host machine filesystem? (and then since /roboflow/.whisper does not exist on the host machine it breaks with "no such file or directory, unlink '/roboflow/.whisper/recording.wav'")

**Comment by tonylampada** [comment]
some more info 
![CleanShot 2024-02-08 at 14 57 42@2x](https://github.com/martin-opensky/whisper-assistant-vscode/assets/218821/8a0e1bbc-d6ef-4ceb-b562-d61daebb8d4d)

**Comment by martin-opensky** [comment]
Thanks for the info however I cannot provide support if you are using Roboflow containers. 

I recommend trying the extension when opening a folder on the local filesystem as this is the only way I have used the extension before.

**Comment by tonylampada** [comment]
OK. Just for clarification - I'm using a devcontainer that happens to be called roboflow.
Devcontainers are a pretty standard vscode functionality.

**Comment by martin-opensky** [comment]
Hey @tonylampada 
I'm primarily working with Typescript / Next.js projects currently so I haven't needed to use the dev containers extension as yet.  If I get chance to look into making Whisper Assistant work with devcontainers I will take a look but I'm pretty busy at the moment with my existing workload so it may be a while!

I recommend that you confirm you can get the Whisper Assistant working by opening a folder on your local filesystem.  Once this is confirmed please consider looking into the issue with the devcontainers yourself and if needed send over a PR once the issue is resolved.  

It'd be great to have some contributions to the project for these kinds of use cases, that I don't have any experience with or an immediate need for.
